Swaply/Items/urls.py
from django.urls import path

from . import views

app_name = 'Items'
urlpatterns = [
    path('<int:pk>',views.detail,name='detail'),
]

Swaply/Swaply/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('item/', include('Items.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Swaply/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup')
]

Swaply/Items/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

Swaply/core/models.py
from django.db import models

# Create your models here.

Swaply/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')
        

Swaply/Items/views.py
from django.shortcuts import get_object_or_404, render

from .models import Item


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    context = {'item':item, 'related_items':related_items}
    return render(request, 'item/detail.html', context)

Swaply/core/views.py
from core.forms import SignUpForm
from django.shortcuts import render
from Items.models import Category, Item


def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    context = {'categories': categories, 'items': items}
    return render(request, 'core/index.html', context)

def contact(request):
    return render ( request , "core/contact.html" )

def signup(request):
    form = SignUpForm()

    context = {'form':form}
    return render(request, 'core/signup.html', context)

Swaply/Items/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}
    {{ item.name }}
{% endblock title %}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3">
            <img src="{{ item.image.url }}" class="rounded-xl">
        </div>

        <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
            <p class="text-gray-500"><strong>Price: </strong>{{ item.price }}</p>
            <p class="text-gray-500"><strong>Seller: </strong>{{ item.created_by }}</p>
            
            {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description: </strong><br>
                {{ item.description }}
            </p>

            <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">Contact Seller</a>
            {% endif %}
                
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Related Items</h2>
        <div class="grid grid-cols-3 gap-3">
            
            {% for item in related_items %}
            <div>
                <a href="{% url 'Items:detail' item.id %}">
                 <div>
                     <img src="{{ item.image.url }}" class="rounded-t-xl w-32 h-32">
                 </div>

                 <div class="p-6 bg-white rounded-b-xl">
                     <h2 class="text-2xl">{{ item.name }}</h2>
                     <p class="text-gray-500">Price: {{  item.price}}</p>
                 </div>
                </a>
             </div>
         
            {% endfor %}
                
        </div>
    </div>
{% endblock content %}
    

Swaply/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>


    <title>
    {% block title %}{% endblock title %}
        | Swaply</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Swaply</a>
        <div class="space-x-6">
            <a href="#" class="text-lg font-semibold hover:text-gray-500">New Item</a>
            <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>

            <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
            <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>


        </div>
    </nav>
  <div class="px-6 py-6">   
    {% block content %}   
    {% endblock content %}     
  </div>  
  <footer class="py-6 px-6 flex justify-between bg-gray-800">
    <div class="w-2/3 pr-10">
        <h3 class="ab-5 font-semibold text-gray-400">About</h3>
        <p class="text-lg text-gray-400">Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem provident quisquam rerum maiores ad, asperiores nemo mollitia iure quae autem itaque temporibus quod dolores at suscipit, ducimus officia perferendis soluta.</p>
    </div>
    <div class="w-1/3">
        <h3 class="ab-5 font-semibold text-gray-400">Menu</h3>

        <ul class="space-y-2">
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
            <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy</a></li>
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms&Conditions</a></li>

        </ul>
    </div>
  </footer>
</body>
</html>

Swaply/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}
   Contact
{% endblock title %}
    
{% block content %}
    <h1>The Contact Page</h1>
{% endblock content %}
     

Swaply/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
    Welcome
{% endblock title %}
    
{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">New Items</h2>
        <div class="grid grid-cols-3 gap-3">
            
            {% for item in items %}
            <div>
                <a href="{% url 'Items:detail' item.id %}">
                 <div>
                     <img src="{{ item.image.url }}" class="rounded-t-xl w-32 h-32">
                 </div>

                 <div class="p-6 bg-white rounded-b-xl">
                     <h2 class="text-2xl">{{ item.name }}</h2>
                     <p class="text-gray-500">Price: {{  item.price}}</p>
                 </div>
                </a>
             </div>
         
            {% endfor %}
                
        </div>
    </div>


    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        <div class="grid grid-cols-3 gap-3 mb-6">
            {% for category in categories %}
            <div>
                <a href="http://">
                 <div class="p-6 bg-white rounded-b-xl">
                     <h2 class="text-2xl">{{ category.name }}</h2>
                     {% if category.items.count > 1 %}
                     <p class="text-gray-500">{{  category.items.count}} items</p>
                     {% else %}
                     <p class="text-gray-500">{{  category.items.count}} item</p>
                     {% endif%}
                 </div>
                </a>
             </div>

        </div>
             {% endfor %}
{% endblock content %}
    

Swaply/core/templates/core/signup.html
{% extends 'core/base.html' %}


{% block title %}
    Sign Up
{% endblock title %}
    

{% block content %}
    <div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Sign Up</h1>
    </div>
{% endblock content %}